language: java
jdk: [openjdk7, oraclejdk7]
before_script: null
script: [mvn test]
env: MAVEN_OPTS="-XX:MaxPermSize=256m"
addons: {firefox: '30.0'}
before_install: ['export DISPLAY=:99.0', sh -e /etc/init.d/xvfb start]
branches:
  only: [v5developer/maven-framework-project-3-origin]
