branches:
  only: [perfectsense/brightspot-cms-1342-origin]
language: java
jdk: [oraclejdk8]
addons:
  apt:
    packages: [oracle-java8-installer]
install: true
script: mvn -Plibrary verify && git clone https://github.com/perfectsense/travis-maven-deploy.git
  && travis-maven-deploy/deploy.sh
