language: java
jdk: [oraclejdk8]
script: mvn clean install -DskipTests=true
services: [redis]
branches:
  only: [debop/hibernate-redis-146-MAVEN_PARALLEL_EXECUTION]
cache:
  directories: [$HOME/.m2, $HOME/.gradle]
