sudo: false
language: java
jdk: [oraclejdk8, openjdk7]
branches:
  only: [Simmetrics/simmetrics-32-origin]
before_install: [mvn clean]
after_success: ['mvn clean cobertura:cobertura coveralls:report -P coveralls.io']
