language: java
jdk: [oraclejdk11]
sudo: required
dist: trusty
env: [MVN_PROFILE=java-8, MVN_PROFILE=java-11]
script: mvn checkstyle:check test -B -V -P ${MVN_PROFILE}
branches:
  only: [finmath/finmath-lib-86-origin]
