language: java
addons:
  hosts: [javasdk]
  hostname: javasdk
jdk: [openjdk7, oraclejdk7, oraclejdk8]
env: ['MODULES_TO_SKIP=\!aws-java-sdk-osgi MAVEN_OPTS=-XX:MaxPermSize=256m', 'MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin,\!aws-java-sdk-opensdk
    MAVEN_OPTS=-XX:MaxPermSize=256m']
matrix:
  exclude:
  - {jdk: openjdk7, env: 'MODULES_TO_SKIP=\!aws-java-sdk-osgi MAVEN_OPTS=-XX:MaxPermSize=256m'}
  - {jdk: oraclejdk7, env: 'MODULES_TO_SKIP=\!aws-java-sdk-osgi MAVEN_OPTS=-XX:MaxPermSize=256m'}
  - {jdk: oraclejdk8, env: 'MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin,\!aws-java-sdk-opensdk
      MAVEN_OPTS=-XX:MaxPermSize=256m'}
notifications:
  email: [github-awsforjava@amazon.com]
install: /bin/true
sudo: required
dist: precise
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script: mvn install -Dhttps.protocols=TLSv1.2 -pl ${MODULES_TO_SKIP}
branches:
  only: [aws/aws-sdk-java-2668-origin]
