sudo: false
language: java
cache:
  directories: [$HOME/.m2]
jdk: [openjdk8]
git: {depth: 3}
branches:
  only: [cpesch/RouteConverter-64-MAVEN_COMPILER_DAEMON]
after_success: |
  curl -Os https://uploader.codecov.io/latest/linux/codecov &&
  chmod +x codecov &&
  ./codecov -t ${CODECOV_TOKEN}
notifications:
  email: [support@routeconverter.com]
