dist: bionic
language: android
jdk: [openjdk12]
android:
  components: [tools, tools, platform-tools, build-tools-24.0.2, android-24, android-23]
cache:
  directories: [$HOME/.m2]
env:
  global: ['MAVEN_OPTS=-Xmx3072m -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled
      -XX:-UseGCOverheadLimit', TRAVIS_NODE_VERSION=6]
before_install: ['echo "MAVEN_OPTS=''-Xmx3072m -XX:MaxPermSize=512m''" > ~/.mavenrc',
  'sudo wget https://apt.llvm.org/llvm.sh', sudo chmod +x llvm.sh, sudo ./llvm.sh
    10, sudo apt-get install -y ocl-icd-opencl-dev clang-10 lldb-10 lld-10 clangd-10,
  'rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd
    ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh
    && nvm install $TRAVIS_NODE_VERSION', npm install, npm install electron-packager
    -g, npm install cordova -g, npm install bower -g, npm install vulcanize -g, 'git
    clone https://github.com/mirkosertic/Bytecoder.git ./bytecoder', cd bytecoder,
  'mvn -pl ''!:bytecoder-integrationtest'' clean install -P notest', cd .., env]
branches:
  only: [mirkosertic/GameComposer-324-origin]
