language: java
cache:
  directories: [~/.m2]
git: {depth: 1}
branches:
  only: [unidal/frameworks-30-origin]
install: mvn install -Dmaven.test.skip -B -fae -s settings.xml
script: mvn test -B -fae -s settings.xml
