name: Build 
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v1
     - uses: joschi/setup-jdk@v1
       env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       with:
           java-version: '12'
     - uses: actions/setup-node@v1
       with:
          node-version: '6'
     - run: npm install
     - run: npm install electron-packager -g
     - run: npm install cordova -g
     - run: npm install bower -g
     - run: npm install vulcanize -g
     - run: wget https://apt.llvm.org/llvm.sh
     - run: chmod +x llvm.sh
     - run: sudo ./llvm.sh 10
     - run: sudo apt-get install -y ocl-icd-opencl-dev clang-10 lldb-10 lld-10 clangd-10
     - run: mvn verify
     - uses: actions/upload-artifact@v1
       with:
         name: Games
         path: 'examples/target/games'